version: '3.3'

networks: 
  default:
    external:
      name: shared
  internal:

services:
  postgres:
    image: mdillon/postgis:11
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
      #- ./dumps:/docker-entrypoint-initdb.d
    networks:
      - internal
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    env_file: .env
    depends_on:
    - "postgres"
    restart: always
    networks:
      - default
      - internal
    ports:
      - 8083:8080
volumes:
  db_data:
